### PR TITLE
Use gradle kts

### PR DESCRIPTION
**Pull request by vLuckyyy**
Due to the fact that im need a plugin for bedwars quickly, I decided to contribute to the development of bedwars1058. I don't know if you like the fact that I converted bedwars1058 from maven to gradle kts. But if you find this change useful I would appreciate if you merge my PR otherwise just close it

### CODE REVIEW

**Comment by andrei1058** [comment]
`e: C:\Users\****\IdeaProjects\BedWars1058\resetadapter_slime\build.gradle.kts:6:5: Unresolved reference: providedCompile`

**Comment by JT122406** [comment]
I would like this merged in the future @vLuckyyy Can you resolve conflicts

**Comment by tomkeuper** [comment]
What does this benefit tho?

**Comment by JT122406** [comment]
Gradle is much faster than maven

**Comment by tomkeuper** [comment]
Im going to leave this up to Andrei to decicde.

**Comment by andrei1058** [comment]
Is it poosible to keep them both? I'd like to give people the option to use maven if they want. Consider how many forks are currently running on maven and they could have CI/CD integrations

**Comment by JT122406** [comment]
> Is it poosible to keep them both? I'd like to give people the option to use maven if they want. Consider how many forks are currently running on maven and they could have CI/CD integrations

So like techincally you could and then people can just load the build system they want to use but personality doesn't make much sense as gradle is just so much faster and better its a waste of time to maintain both build systems

**Comment by JT122406** [comment]
@vLuckyyy Can you update gradle to 8.0.2

**Comment by vLuckyyy** [comment]
> @vLuckyyy Can you update gradle to 8.0.2

Yes, later

**Pull request closed without merging**
