### PR TITLE
Fix https://github.com/andrei1058/BedWars1058/issues/824

### LINKED ISSUE #824: When the backpack is full, players cannot be given the items they purchased
When the backpack is full, players cannot be given the items they purchased.
Hypixel will prompt that the backpack is full. How can BedWars1058 achieve this function

### PR DESCRIPTION
**Pull request by ImYenil**
Fix https://github.com/andrei1058/BedWars1058/issues/824

### CODE REVIEW

**Comment by Lsy-291** [comment]
https://github.com/Lsy-291/Advanced-BedWars1058/commit/2cf6c22d23724105cb9f97db8aa1e6745de650ed

**Comment by andrei1058** [comment]
It needs to be improved. If you are buying something that something can be stacked on your current items. What you are doing here is only searching for an empty slot which is not what we want to achieve.

**Comment by andrei1058** [comment]
@Lsy-291 from what I see your fork does not respect my license. Please **revert** LICENSE.md and make sure to be compliant.

**Comment by Lsy-291** [comment]
> @Lsy-291 from what I see your fork does not respect my license. Please **revert** LICENSE.md and make sure to be compliant.

I lost it. Sorry, I will make it up

**Comment by andrei1058** [comment]
Does it still stack items when possible?

**Pull request closed without merging**
