### PR TITLE
Added bungeecord servers compatibility

### PR DESCRIPTION
**Pull request by KikyoC**
Hello,
If you want to try it, you just have to put server:bungee_server_name as a command on an item.

### CODE REVIEW

**Comment by andrei1058** [comment]
looks good, but what is this for?

**Comment by KikyoC** [comment]
For example. If you are in bedwars lobby and you want to got to main lobby (by clicking ont the bed), you can't run bungeecord commands. So I added this. (because I asked here: https://discord.com/channels/201345265821679617/348088106546757653/1167752843059544134)

**Comment by andrei1058** [comment]
What about bw leave?

Il Mar 31 Ott 2023, 19:51 Tom ***@***.***> ha scritto:

**Comment by KikyoC** [comment]
bw leave is not when you are waiting in a game and you want to leave ?

**Comment by andrei1058** [comment]
> bw leave is not when you are waiting in a game and you want to leave ?

in a bungee network context it acts as leave command. iirc bedwars will also register a /leave command when bungee is set to true in spigot.yml.

**Pull request closed without merging**
