### PR TITLE
Levelling System Update

### PR DESCRIPTION
**Pull request by Xxyuri2005xX**
Updated the Bedwars1058 Levelling System with the missing Listeners
- Bed Break
- Regular Kill
- Final Kill

I also made a Youtube Video to show it during a Game.

https://www.youtube.com/watch?v=3PlhPVQTgs8

Everythin g got tested more that 5 times before pulling.

### CODE REVIEW

**Comment by Xxyuri2005xX** [comment]
there are some errors, i fix and i re-open the Request

**Comment by andrei1058** [comment]
please align with master

**Comment by Xxyuri2005xX** [comment]
do i need to make any changes to the code?

**Comment by ajgeiss0702** [comment]
Resolve the conflicts. GitHub has a message about it

**Comment by Xxyuri2005xX** [comment]
i'm working on Intellij for solving the conflicts and fixing my errors

**Pull request closed without merging**
