### PR TITLE
WIP: Autoscale everything

### PR DESCRIPTION
**Pull request by ajgeiss0702**
Allow autoscale to be used on all serverTypes

Would also allow disabling of autoscale on bungee mode (which wasn't really possible before without making arenas not reset)

TODO:
- [x] Pry autoscale out from being only multiarena
- [x] Make BUNGEE_LEGACY be its own thing, not just BUNGEE but without autoscale
- [x] Make the arena selector work with cloned arenas
- [x] Make signs work with cloned arenas
- [ ] Make join commands work (they seemingly already do but should probably be checked)
- [x] Fix issue with arenas de-scaling even with players in them, making a broken game
    * ~~There also seems to be an issue with worlds not being unloaded? Needs more investigation~~
    * Turns out it was the private games addon. Mher is working on it
- [ ] Probably other stuff that comes up during testing

Note to self: Dont forget to test with
- [x] Internal adapter (MULTIARENA)
- [ ] Internal adapter (SHARED)
- [ ] Internal adapter (BUNGEE)
- [ ] Internal adapter (BUNGEE_LEGACY)
- [ ] SWM (MULTIARENA)
- [ ] SWM (SHARED)
- [ ] SWM (BUNGEE)
- [ ] SWM (BUNGEE_LEGACY)
And no me, don't be lazy and skip testing the bungee things, because I could have easily messed something up there on accident

### CODE REVIEW

**Comment by sreyas0001** [comment]
What does this do

**Comment by ajgeiss0702** [comment]
> What does this do

read the description ;)

**Comment by WaifChan** [comment]
waiting for done!
thanks aj

**Comment by Eradiator** [comment]
I Have  been wanting this for so long.
please also make configurable serverID for cloned maps

**Comment by sreyas0001** [comment]
Will this be implemented in the next-update, I would like to see it 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by ajgeiss0702** [comment]
> Will this be implemented in the next-update, I would like to see it 👍 👍 👍 👍 👍 👍 👍 👍

It probably won’t be done by then. There’s a lot to test once I finish it

**Comment by andrei1058** [comment]
masochist >.<

**Comment by sreyas0001** [comment]
waiting for updates
lol
waiting for all task completion

**Comment by Eradiator** [comment]
> waiting for updates lol waiting for all task completion

Yea, Me2 waiting for COMPLETION😄😄😄

**Pull request closed without merging**
