### PR TITLE
Added Winstreaks(Altering the table this time), Unranked Arenas, Custom Arena constructor, Fixed Scoreboard shuffle, Fixed breakable items.

### PR DESCRIPTION
**Pull request by MrF1yn**
Placeholder for winstreak: %bw1058_stats_winstreak%
Added a toggle 'updateStats' in arenas.yml which on setting it to false will prevent any stats from getting updated during a game in that arena(if you want to have an unranked arena in the same server)

Added a constructor in Arena.java with extra parameters such as world check bypass and Custom arena config. This will allow plugins to create games with custom properties(also need for my server so i thought other people could make use of it too)

Also i made a pull request to BWproxy to add the winstreak there too.

### CODE REVIEW

**Comment by ghost** [comment]
What is unranked arenas and Custom arena construction

**Comment by MrF1yn** [comment]
so theres a new option in arenas config called updateStats, if you set it to false it will not update any stats for players who play in that arena so for e.g if you play in that arena then you kills,bed breaks etc etc will not increase.
 And for the custom constructor its basically allows other plugins to define their own arena config and load it in a standard bedwars arena(idk if that makes sense look at the changes if you dont understand)

**Comment by andrei1058** [comment]
If other plugins want to make custom areans, they should implement IArena and make their own logic. I also don't understand why you make items unbreakable by default. That's wrong to me. You define in shop configuration what must be unbreakable.

**Comment by MrF1yn** [comment]
Alright I'll do that then.

**Pull request closed without merging**
