### PR TITLE
Change player's gamemode to adventure in the waiting lobby (FIXED)

### PR DESCRIPTION
**Pull request by FabrisNick**

### CODE REVIEW

**Comment by andrei1058** [comment]
Can you please explain what you're doing here?

**Comment by MherZaqaryan** [comment]
This seems wrong, but what if I want to have survival mode on the waiting lobby, this should probably be configurable!

**Comment by FabrisNick** [comment]
> Can you please explain what you're doing here?

When a player join an arena and it's not started, his gamemode will be adventure. Like Hypixel.

**Comment by andrei1058** [comment]
I don't know if we rellay want that. Please open an issue before working on pull requests so we can vote. Also, if you want to contribute have a look at the issues page and maybe help us with pull requests for issues marked as begginer or help-wanted. Reading CONTRIBUTING.md might be helpful.

**Pull request closed without merging**
