### PR TITLE
PAPI and bug!!!

### PR DESCRIPTION
**Pull request by dyslmj**
希望能增加竞技场状态的运算符
Would like to add the arena state operator and Fireballs do not propel or break blocks in spigotmc 1.8.8. in the BedWars-21.11.2 version if it breaks the blocks but the explosion was not propelling.
The following variables are very unstable and error prone in TRHD!
- '&e1. &b%ajleaderboards_board_bw1058_player_level_raw_1_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_1_value%'
- '&e2. &b%ajleaderboards_board_bw1058_player_level_raw_2_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_2_value%'
- '&e3. &b%ajleaderboards_board_bw1058_player_level_raw_3_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_3_value%'
- '&e4. &b%ajleaderboards_board_bw1058_player_level_raw_4_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_4_value%'
- '&e5. &b%ajleaderboards_board_bw1058_player_level_raw_5_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_5_value%'
- '&e6. &b%ajleaderboards_board_bw1058_player_level_raw_6_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_6_value%'
- '&e7. &b%ajleaderboards_board_bw1058_player_level_raw_7_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_7_value%'
- '&e8. &b%ajleaderboards_board_bw1058_player_level_raw_8_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_8_value%'
- '&e9. &b%ajleaderboards_board_bw1058_player_level_raw_9_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_9_value%'
- '&e10. &b%ajleaderboards_board_bw1058_player_level_raw_10_name% &7- &e%ajleaderboards_board_bw1058_player_level_raw_10_value%'

### CODE REVIEW

**Comment by ajgeiss0702** [comment]
Wtf is this

**Comment by ajgeiss0702** [comment]
This is a pull request. I think you meant to create an issue

**Comment by dyslmj** [comment]
> 

yes

**Comment by dyslmj** [comment]
OK I&#39;m Sent the questions to the questions section！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月25日(星期六) 中午12:31
收件人: "andrei1058/BedWars1058";
抄送: "Author";
主题: Re: [andrei1058/BedWars1058] PAPI and bug!!! (PR #225)





 
Closed #225.
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
