### PR TITLE
Better Shop Config

### PR DESCRIPTION
**Pull request by ghost**
Emerald 1 for bridge egg
Gold 5 for KB Stick
Change some item names that displays in inventory

### CODE REVIEW

**Comment by andrei1058** [comment]
What is this supposed to mean? **Read CONTRIBUTING.md**

**Comment by ghost** [comment]
Actually I don't exactly know what hypixels new shop items cost but what i have seen in youtuber's video is what i changed in the ShopManager.java

**Comment by minhh2792** [comment]
omg dude

**Comment by TheWylot** [comment]
it can be better

**Review by TheWylot — CHANGES_REQUESTED** [review]
it can be better a lot

**Pull request closed without merging**
