### PR TITLE
Java 11 Minimum Requirement

### PR DESCRIPTION
**Pull request by JT122406**

### CODE REVIEW

**Comment by neziw** [comment]
What about 1.8 versions? Normal Spigot and Paper don't support Java 11.

**Comment by JT122406** [comment]
> What about 1.8 versions? Normal Spigot and Paper don't support Java 11.

They do support Java 11 I have tried on my systems

**Comment by Eradiator** [comment]
> What about 1.8 versions? Normal Spigot and Paper don't support Java 11.



> > What about 1.8 versions? Normal Spigot and Paper don't support Java 11.
> 
> They do support Java 11 I have tried on my systems

Actually spigot/paper 1.8.9 doesnt work properly on java 11 on Linux

**Comment by lunoxxofficial** [comment]
> > What about 1.8 versions? Normal Spigot and Paper don't support Java 11.
> 
> > > What about 1.8 versions? Normal Spigot and Paper don't support Java 11.
> > 
> > 
> > They do support Java 11 I have tried on my systems
> 
> Actually spigot/paper 1.8.9 doesnt work properly on java 11 on Linux

We have to use a fork like nacho spigot
(https://github.com/CobbleSword/NachoSpigot)

**Comment by RinR1nMC** [comment]
Java 11 Minimum requirement 
If you are using 1.8 You Must Uninstall some plugins like FAWE,Alosno Leagues because those are unsupported java 11 for 1.8 plugins

**Comment by Memexurer** [comment]
why would anyone need this? bw1058 works normally on java 11, and not everyone has j11...

**Pull request merged**
