### PR TITLE
Add 1.18.2 support

### PR DESCRIPTION
**Pull request by Krakenied**

### CODE REVIEW

**Comment by abhishekairan** [comment]
Hyy Krakenied can you please provide me a jar with 1.18.2 support i need it and idk when 1.18.2 support will be added to main branch, kindly pls provide me with a bedwars 1.18.2 supported jar 🥺

**Comment by KadTheAad** [comment]
> Hyy Krakenied can you please provide me a jar with 1.18.2 support i need it and idk when 1.18.2 support will be added to main branch, kindly pls provide me with a bedwars 1.18.2 supported jar 🥺

You can compile it yourself

**Comment by abhishekairan** [comment]
> > Hyy Krakenied can you please provide me a jar with 1.18.2 support i need it and idk when 1.18.2 support will be added to main branch, kindly pls provide me with a bedwars 1.18.2 supported jar 🥺
> 
> You can compile it yourself

I don't know how to bro that's why i am asking him

**Comment by abhishekairan** [comment]
> _ No description provided. _

https://pastebin.com/mh3XHtzU

looks like 1.18.2 support is not done properly

**Comment by KadTheAad** [comment]
The scoreboard support isn't added yet

**Comment by KadTheAad** [comment]
> > _ No description provided. _
> 
> https://pastebin.com/mh3XHtzU
> 
> looks like 1.18.2 support is not done properly

Thats because when you compile the version you must use new sidebar api

**Comment by navin-hariharan** [comment]
Can I get a compiled jar file?

**Comment by andrei1058** [comment]
it is sidebar lib dependent. this will not work.

**Comment by BeefyAndTheDucks** [comment]
I have an issue, when compiling, here is my error:
https://pastebin.com/281q8T3i

I'm using Java 17

**Pull request closed without merging**
