### PR TITLE
Fireball Enhancement

### PR DESCRIPTION
**Pull request by Lsy-291**
Fireball can now destroy blocks and supports the following functions
1. Custom destruction radius
2. Whitelist
3. Flip the whitelist
4. Destroy existing blocks in the map
5. The damage range of the block is a sphere
6. Custom Area Protection
7. Explosion particle effect

### CODE REVIEW

**Comment by Lsy-291** [comment]
Two weeks ago, it was still pending review. LMAO, even the new PR than mine, has been approved. Andrei, what are you doing?

**Comment by andrei1058** [comment]
Isn't this related to #469 ? We should implement the protection logic for fireballs there.

**Comment by Lsy-291** [comment]
> 这与#469无关吗？我们应该在那里实现火球的保护逻辑。

Now it has not achieved support for explosion-proof glass

**Comment by Lsy-291** [comment]
> 这与#469无关吗？我们应该在那里实现火球的保护逻辑。

Do you mean that this PR lacks support for explosion-proof glass?

**Comment by andrei1058** [comment]
The other pull request will also protect cumstom areas such as shop etc. Fireballs are explosions, so in the end I think I will implement your logic in the other pull request to make it cleaner.

**Comment by Lsy-291** [comment]
> The other pull request will also protect cumstom areas such as shop etc. Fireballs are explosions, so in the end I think I will implement your logic in the other pull request to make it cleaner.

So it won't be merged?

**Pull request closed without merging**
