### PR TITLE
Hindi Language

### PR DESCRIPTION
**Pull request by Itsmemonzu**
**Hope this helps!**

### CODE REVIEW

**Comment by ajgeiss0702** [comment]
It looks like all of the shop items arent translated. Incomplete languages will not be added.

**Comment by ghost** [comment]
Bruh dont you have any other job

**Comment by andrei1058** [comment]
there are conflicts to be solved

**Comment by Itsmemonzu** [comment]
I tried fixing the conflicts, but it doesn't seem to work for some reason even after updating it twice.

**Pull request merged**
