### PR TITLE
Parties and Friends

### PR DESCRIPTION
**Pull request by JT122406**
Added  support for Parties and Friends Spigot.  Updated dependencies and adjusted party hook system.

### CODE REVIEW

**Review by ajgeiss0702 — APPROVED** [review]
I helped test it

**Comment by ghost** [comment]
Nice but will it work without the friends and parties plugin

**Comment by JT122406** [comment]
Yes it should it checks if parties and friends is enabled before doing anything

**Comment by andrei1058** [comment]
does it work with bedwars-proxy? or in a multi-instance environment?

**Comment by ajgeiss0702** [comment]
> does it work with bedwars-proxy? or in a multi-instance environment?

Its currently only for PAF spigot, which i believe is only meant to be used on a single spigot server. PAF is very confusing so i could be wrong.

**Comment by JT122406** [comment]
This just works in the spigot single server environment I'm trying to port stuff over to the bedwarsproxy but the build on GitHub seems to be broken

**Comment by ghost** [comment]
So if i need to use Party and friends i need to use THat plugin in the server tooo. Bruh i dont have money

**Comment by JT122406** [comment]
or you can use a different party plugin or no party plugin

> So if i need to use Party and friends i need to use THat plugin in the server tooo. Bruh i dont have money

**Comment by ghost** [comment]
> or you can use a different party plugin or no party plugin
> 
> > So if i need to use Party and friends i need to use THat plugin in the server tooo. Bruh i dont have money

I was just curious to know.
1. The party plugin by alessio only has party support no friends support.
2. So if this gets implemented will bedwars plugin have friends support or will i need to have the paid party and friends plugin.??

**Comment by JT122406** [comment]
> > or you can use a different party plugin or no party plugin
> 
> > 
> 
> > > So if i need to use Party and friends i need to use THat plugin in the server tooo. Bruh i dont have money
> 
> 
> 
> I was just curious to know.
> 
> 1. The party plugin by alessio only has party support no friends support.
> 
> 2. So if this gets implemented will bedwars plugin have friends support or will i need to have the paid party and friends plugin.??
> 
> 
Alessio just has parties and not friends, parties and friends has a friends gui built into it.  But it is up to you if you want to use any party plug-in with bedwars

**Pull request merged**
