### PR TITLE
Gradle

### PR DESCRIPTION
**Pull request by dG9hc3Q**
idk if you want it but gradle is cool

### CODE REVIEW

**Comment by rafi67000** [comment]
jesus christ, why

**Comment by dG9hc3Q** [comment]
maven sucks

**Comment by rafi67000** [comment]
why do you think like that

**Comment by andrei1058** [comment]
it's a good thing, but there are some unwanted changes and also we'd like to keep marven as well

**Comment by JT122406** [comment]
Personality Gradle would make this project a lot easier to work on and a lot faster to build @ajgeiss0702 can confirm that as well

**Comment by JT122406** [comment]
However I would prefer to use the Kotlin version of Gradle and not Groovy if possible

**Comment by andrei1058** [comment]
Any help is welcome

**Comment by Eradiator** [comment]
i know you had spend a lot of time for this but i dont think andrei would take this seriously.... no sure.

**Comment by dG9hc3Q** [comment]
Its really quick with `gradle --init`

**Comment by Ixf1nity** [comment]
gradle sucks

**Comment by tomkeuper** [comment]
Thank you for your contribution but im affraid I will have to close this PR as there is another PR with the preferred Gradle KTS

**Pull request closed without merging**
