### PR TITLE
Full translate of Russian.java

### PR DESCRIPTION
**Pull request by werxqq0**
I translated 100% of Russian language file

### CODE REVIEW

**Review by tomkeuper — APPROVED** [review]

**Comment by andrei1058** [comment]
Accoding to reverso.net some of your translations are actually worse

**Comment by tomkeuper** [comment]
@UnMatveev can you rougly explain what you changed on the existing translations and maybe you also know why a translator website would say its worse. I know it sometimes happens with certain languages but I guess you would know that better with russian

**Comment by werxqq0** [comment]
> Accoding to reverso.net some of your translations are actually worse

hm.. Russian is my native language, there is all right. I show my translation to many Russian friends, they say it looks beatiful. And in my translate, i actually using slang. And when i translate "party" (for example) its translate, like "group" in Russian, but all using slang "party", i dont see a Russian mate who calls "party" as a "group", by the way its look strange, and i use slang, because many peoples can dont get it. Sorry for troubles, but translate is accurate and good.

**Comment by werxqq0** [comment]
> what you changed on the existing translations

i translated shop, upgrades, all messages, scoreboards, and e.t.c.
by the way, i changed 25-30% of old translate, because its awful

**Review by tomkeuper — APPROVED** [review]

**Pull request merged**
