### PR TITLE
Added Winstreak(new database table) Stats, Fixed scoreboard sorting, Fixed Items loosing durability.

### PR DESCRIPTION
**Pull request by MrF1yn**
Winstreak table name is 'WinStreak' and placeholder is %bw1058_stats_winstreak%
Added option in arenas.yml to toggle teamShuffle on or off.
Made all items unbreakable in shop.

### CODE REVIEW

**Comment by MrF1yn** [comment]
I also made a pull request in bedwars proxy which adds the winstreak stats there too.

**Comment by ghost** [comment]
Can you somehow add kill streak death streak etc would've been better

**Comment by ghost** [comment]
Also make winstreak for different arenagroups

**Comment by MrF1yn** [comment]
Alright I will try doin that

**Comment by MherZaqaryan** [comment]
This one also seems wrong because you made a new table for win streaks, I meant that you can add the column on the global_stats

**Comment by MrF1yn** [comment]
bruh you mean using the ALTER table query?

**Comment by MherZaqaryan** [comment]
> bruh you mean using the ALTER table query?

Yep, that's exactly what I mean!

**Comment by MrF1yn** [comment]
Alright I'll do it then

**Pull request closed without merging**
