### PR TITLE
Fix fireballs on 1.12

### LINKED ISSUE #214: Fireball not working on 1.12
**Describe the bug**
Fireball didn't work on version 21.12.1, when I right click it didn't even destroy block or deal damage to player

Here is the video: https://youtu.be/ZmcrdrcJSHo

**To Reproduce**
1. Install BedWars1058 21.12.1 (Downloaded from Polymart)
2. Join a game
3. Buy fireball from shop
4. Facing this issue

**Expected behavior**
Fireball should work fine

**System (please complete the following information):**
 - OS: Ubuntu 
 - Server software: PaperMC
 - Server Version: 1.12.2
 - Plugin Version: 21.12.1

### PR DESCRIPTION
**Pull request by ajgeiss0702**
Tested on:
1.8.8
1.12.2
1.16.5

Fixed fireballs not doing anything on 1.12 (and 1.8 too for some people it seems like, but not everyone)

fixes #214

### CODE REVIEW

**Review by ProtoGhost — APPROVED** [review]

**Comment by ghost** [comment]
Nice

**Comment by TheWylot** [comment]
gg

**Comment by ghost** [comment]
Make 2.0 horizontal and 0.65/0.50 vertical

**Review by ghost — COMMENTED** [review]
@ajgeiss0702 What does the negative value of horizontal kb do in the
bedwars-plugin/src/main/java/com/andrei1058/bedwars/configuration/MainConfig.java

**Comment by ajgeiss0702** [comment]
> @ajgeiss0702 What does the negative value of horizontal kb do in the
> bedwars-plugin/src/main/java/com/andrei1058/bedwars/configuration/MainConfig.java

It’s not negative

**Comment by TrianglyRU** [comment]
My friend compiled the plugin with your changes, knockback and stuff works but fireball now destoys ALL kind of blocks (even Obsidian!) except for the glass

https://user-images.githubusercontent.com/45323263/148672681-43651e24-f5dc-45d7-b342-3eb3d5046d58.mp4

Paper 1.12.2

**Comment by ajgeiss0702** [comment]
Yeah, I think I might have found the solution to the original issue.

If you have the original issue (of fireballs not doing anything), can you check server.properties and make sure spawn-protection is 0?

**Comment by TrianglyRU** [comment]
Yeah, it is 0

**Comment by andrei1058** [comment]
any fix for the block damage thing?

**Comment by ajgeiss0702** [comment]
@andrei1058 this PR is finally ready to be merged.

all options work as intended. tested on 1.12.2

The only thing that needs work is blocks explosing behind glass, but thats a thing with explosions overall, not just fireballs so that can be a differnet pr

**Pull request merged**
