### PR TITLE
Allows the Bow Hit message to be disabled (FIXED)

### PR DESCRIPTION
**Pull request by FabrisNick**
added the ability to set Messages.PLAYER_HIT_BOW to empty to disable the message

### CODE REVIEW

**Review by ajgeiss0702 — APPROVED** [review]
Looks good to me (although you didnt have to use the StringUtils class)

**Review by andrei1058 — CHANGES_REQUESTED** [review]
Iirc string utils is not compiled in all versions, so this may break multi version support.

**Comment by FabrisNick** [comment]
> Iirc string utils is not compiled in all versions, so this may break multi version support.

Now use String.length == 0

**Comment by ajgeiss0702** [comment]
You could use .isEmpty()

**Review by andrei1058 — APPROVED** [review]

**Pull request merged**
