### PR TITLE
Added Winstreak stats, Toggleable Team shuffle, Unbreakable items.

### PR DESCRIPTION
**Pull request by MrF1yn**
Winstreak stats placeholder - %bw1058_stats_winstreak%
Added teamshuffle toggle in arenas.yml(turning it off will sort the teams in scoreboard according to hypixel sorting standards)
Fixed a bug were items such as (sword, picks etc) were loosing durability.

### CODE REVIEW

**Comment by MrF1yn** [comment]
I tested everything and it should work

**Comment by MherZaqaryan** [comment]
> I tested everything and it should work

It will work for new users only since it's not overwriting old users' databases!
Check the database availability if it's available append a new column otherwise create a table.

I am also planning to add per group statistics, so I would really recommend doing this.

**Comment by MrF1yn** [comment]
alright doin it

**Comment by MherZaqaryan** [comment]
> alright doin it

image

By the way, this is not really required here.
You also changed the plugin name here.

**Comment by MrF1yn** [comment]
yea ignore that actually remove that i made this fork for my own server so i added it but i forgot to remove it so..

**Comment by ghost** [comment]
What does unbreakable item stand for

**Comment by MrF1yn** [comment]
> What does unbreakable item stand for

bascically when you buy swords, picks etc etc and use them then they loose their durability(which they should not) so i made it unbreakable so it doesnt loose durability

**Comment by ghost** [comment]
What does toggle team shuffle do does it solve the scoreboard sorting problem

**Comment by MrF1yn** [comment]
Yes it does

**Pull request closed without merging**
