### PR TITLE
Create Indonesia Languange

### PR DESCRIPTION
**Pull request by ArachneXD**
BedWars1058 Indonesia Languange | Made By JektDV

### CODE REVIEW

**Comment by ajgeiss0702** [comment]
It looks like there are several English strings in the shop section

**Comment by ajgeiss0702** [comment]
It also looks like you forgot to initialize the language (so it won’t work)
For an example, you can see here: https://github.com/andrei1058/BedWars1058/pull/369/files

**Comment by ArachneXD** [comment]
First, I didn't change the language because Indonesian is too awkward and looks weird, so I decided to use English, and secondly, I'll fix it. Thank you :)

**Comment by ArachneXD** [comment]
But I will still improve on the shop menu whose language is English, I will replace it 100%

**Pull request closed without merging**
