### PR TITLE
After repairing and upgrading to sharpness, swords in ender chests will not gain enchantment

### PR DESCRIPTION
**Pull request by Lsy-291**
After the repair team upgrades the Sharp Enchantment, the sword in Enderchest will not be enchanted
#783

### CODE REVIEW

**Comment by andrei1058** [comment]
I think the best way to do this is adding the enchanting code in 
Interact#164 with an else and then add the owner#getSwordsEnchantments() to the swords in the opened inventory.

image

**Comment by andrei1058** [comment]
Actually check if owner#isMember because this if is negated

**Comment by Lsy-291** [comment]
> 

Yes, I thought for a moment, and my solution to it is indeed not appropriate. It will result in the sword that is purchased with a sharp enchantment and then placed in the chest/enderchest still unable to obtain the enchantment

**Comment by Lsy-291** [comment]
> > 
> 
> 是的，我想了一会儿，我的解决方案确实不合适。这将导致购买带有锋利附魔的剑，然后放入胸部/尾部箱中仍然无法获得附魔



> 我认为最好的方法是在 Interact#164 中添加附魔代码与 else ，然后将所有者 #getSwordsEnchantments（） 添加到打开的物品栏中的剑中。
> 
> 图像

I will rewrite it in the near future

**Pull request closed without merging**
