### PR TITLE
1.18.2 Support (Beta)

### LINKED ISSUE #450: Feature Request/Bug Report: Currently 1.18.2 isn't supported
**Is your feature request related to a problem? Please describe.**
When running the plugin under 1.18.2 it logs this error:
[04:10:31] [Server thread/INFO]: [BedWars1058] Loading BedWars1058 v22.2
[04:10:31] [Server thread/ERROR]: [BedWars1058] I can't run on your version: v1_18_R2

**Describe the solution you'd like**
Support for 1.18.2

**Describe alternatives you've considered**
Since 1.18.2 is the current newest version and supporting that would also help with supporting future versions, there are no real alternatives.

**Additional context**
Server version: git-Paper-267 (MC: 1.18.2)
Java version: openjdk 17.0.2 2022-01-18
Plugin version: bedwars-plugin-22.2

### PR DESCRIPTION
**Pull request by JT122406**

### CODE REVIEW

**Comment by JT122406** [comment]
Bedwars1058 no longer disables on 1.18.2;  I am unsure if everything works but basic support is here we can just put (Beta) next to 1.18.2 for the time being

**Comment by ltjessem** [comment]
Tried this, loading the plugin and initial arena setup worked fine but it starts spitting out errors afterwards:

`[07:06:16 WARN]: [BedWars1058] Task #3678 for BedWars1058 v22.3-SNAPSHOT generated an exception
java.lang.IllegalStateException: java.lang.InstantiationException: Server not supported.
        at com.andrei1058.bedwars.sidebar.BedWarsScoreboard.<init>(BedWarsScoreboard.java:117) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.sidebar.BedWarsScoreboard.lambda$giveScoreboard$27(BedWarsScoreboard.java:626) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-234]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-234]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.InstantiationException: Server not supported.
        at com.andrei1058.bedwars.libs.sidebar.SidebarManager.<init>(SidebarManager.java:40) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.sidebar.BedWarsScoreboard.<init>(BedWarsScoreboard.java:115) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?]
        ... 9 more
`

`Caused by: java.lang.InstantiationException: Server not supported.
        at com.andrei1058.bedwars.libs.sidebar.SidebarManager.<init>(SidebarManager.java:40) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.sidebar.BedWarsScoreboard.<init>(BedWarsScoreboard.java:115) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.sidebar.BedWarsScoreboard.giveScoreboard(BedWarsScoreboard.java:628) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.arena.Arena.lambda$changeStatus$12(Arena.java:1489) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.andrei1058.bedwars.arena.Arena.changeStatus(Arena.java:1489) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.arena.Arena.addPlayer(Arena.java:527) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.commands.bedwars.subcmds.regular.CmdJoin.execute(CmdJoin.java:77) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?]
        at com.andrei1058.bedwars.commands.bedwars.MainCommand.execute(MainCommand.java:150) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 20 more
`

**Comment by JT122406** [comment]
> Tried this, loading the plugin and initial arena setup worked fine but it starts spitting out errors afterwards:
> 
> `[07:06:16 WARN]: [BedWars1058] Task #3678 for BedWars1058 v22.3-SNAPSHOT generated an exception java.lang.IllegalStateException: java.lang.InstantiationException: Server not supported. at com.andrei1058.bedwars.sidebar.BedWarsScoreboard.<init>(BedWarsScoreboard.java:117) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?] at com.andrei1058.bedwars.sidebar.BedWarsScoreboard.lambda$giveScoreboard$27(BedWarsScoreboard.java:626) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-234] at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-234] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.18.2.jar:git-Paper-234] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-234] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[paper-1.18.2.jar:git-Paper-234] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[paper-1.18.2.jar:git-Paper-234] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-234] at java.lang.Thread.run(Thread.java:833) ~[?:?] Caused by: java.lang.InstantiationException: Server not supported. at com.andrei1058.bedwars.libs.sidebar.SidebarManager.<init>(SidebarManager.java:40) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?] at com.andrei1058.bedwars.sidebar.BedWarsScoreboard.<init>(BedWarsScoreboard.java:115) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?] ... 9 more `
> 
> `Caused by: java.lang.InstantiationException: Server not supported. at com.andrei1058.bedwars.libs.sidebar.SidebarManager.<init>(SidebarManager.java:40) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?] at com.andrei1058.bedwars.sidebar.BedWarsScoreboard.<init>(BedWarsScoreboard.java:115) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?] at com.andrei1058.bedwars.sidebar.BedWarsScoreboard.giveScoreboard(BedWarsScoreboard.java:628) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?] at com.andrei1058.bedwars.arena.Arena.lambda$changeStatus$12(Arena.java:1489) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?] at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] at com.andrei1058.bedwars.arena.Arena.changeStatus(Arena.java:1489) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?] at com.andrei1058.bedwars.arena.Arena.addPlayer(Arena.java:527) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?] at com.andrei1058.bedwars.commands.bedwars.subcmds.regular.CmdJoin.execute(CmdJoin.java:77) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?] at com.andrei1058.bedwars.commands.bedwars.MainCommand.execute(MainCommand.java:150) ~[bedwars-plugin-22.3-SNAPSHOT.jar:?] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?] ... 20 more`

That was just because you compiled it before sidebar api supported 1.18.2

**Comment by darkwon** [comment]
@JT122406 is there a jar download file for this beta version ?

**Pull request closed without merging**
