### PR TITLE
Portuguese Language

### PR DESCRIPTION
**Pull request by DeusDrizzyy**
Add Portuguese language.

### CODE REVIEW

**Comment by ghost** [comment]
NoOne(most) even uses languages other than English..
You can just make your custom one for your own

**Comment by DeusDrizzyy** [comment]
> NoOne(most) even uses languages other than English.. You can just make your custom one for your own

This plugin is already used by thousands of people from all over the world, and Google Translate's translation is not always accurate, it is important to add new languages to make life easier for users. 
In addition, the purpose of the translations is to allow players to enjoy the bedwars server in their native language, bringing a better gaming experience to those who do not know English.

**Comment by ghost** [comment]
I wish there was only one language all over the world English Then I could have spoke to everyone

**Comment by minhh2792** [comment]
I wish you stop using Github

**Comment by ghost** [comment]
> I wish you stop using Github

I wish you stop living in this verse

**Pull request merged**
