### PR TITLE
Remove Support for certain versions 

### PR DESCRIPTION
**Pull request by JT122406**
Removed support for:
1.9.4 (v1_9_R2)
1.10 - 1.10.2 (v1_10_R1)
1.11 (v1_11_R1)
1.13.1 - 1.13.2 (v1_13_R2)
1.14 - 1.14.2 (v1_14_R1)
1.15 - 1.15.2 (v1_15_R1)
1.16 - 1.16.3 (v1_16_R1/2)

### CODE REVIEW

**Comment by Eradiator** [comment]
Its not required to be removed but no one uses/only a few people uses it in there versions

**Comment by Eradiator** [comment]
> Its not required to be removed but no one uses/only a few people uses it in there versions

can maybe reduce the plugin  size

**Comment by andrei1058** [comment]
resolve conflicts

**Comment by JT122406** [comment]
Conflicts are fixed now I believe

**Comment by 80486gx2** [comment]
Why? is it really that bad for these versions to be supported?

**Comment by Memexurer** [comment]
nobody plays on these versions afaik

**Pull request merged**
