### PR TITLE
Small Optimization

### PR DESCRIPTION
**Pull request by m7mqdev**
# Description of the Change
 - Changed configuration files loading to make the conversion faster and easier to read.
 - Added a PrimitiveUtil class that handles the primitive types casting more efficiently.
# Quantitative Performance Benefits
It matters a lot in the loading process, because you were saving the YamlConfiguration instance to the file everytime you change a value, I changed that in someway to decrease those saves without editing the base code.

### CODE REVIEW

**Comment by m7mqdev** [comment]
Hello, yesterday I was half asleep when I modified the getCurrentVersion, I removed importamt cases in the switch statement, I will bring it back when I get in the pc. 

Edit: I did it. Changes to BedWars#getCurrentVersion were cancelled.

**Comment by tomkeuper** [comment]
Code looks good to be but I would like to see a bit more documentation, definitly on the convert functions. 
I also saw you implemented some functions in the mainConfig related to a lang being disabled but this is not mentioned in your pr/commits. 

If you could add some more docs I can approve this pr

**Comment by m7mqdev** [comment]
Yes sounds like I forgot about adding documentation or mentioning the language loading, but you can easily know what is the purpose of the code from it's context, PrimitiveUtil class is the same as the NumberConversion class which is made by Bukkit, but it doesn't deeply search for the number's value, which happens too behind the scene in the ConfigurationSection class (it doesn't deeply search for the number's value).
I enhanced the language loading/disabling system and I will add documentation to it's changes later to make it more easier to read, even if I think you can easily read it since it's not that complex.

**Comment by tomkeuper** [comment]
I agree with your answer but imo code should be documented definitly when the rest is too. 
eg. even the reload function in that class has a description.

**Comment by andrei1058** [comment]
Looks good, but why not removing old paths?

**Comment by m7mqdev** [comment]
I don't think I as a contributor should consider removing old paths or not, so I enhanced the code to handle old paths better.

**Comment by tomkeuper** [comment]
If paths arent used anymore there is no reason to keep them, and as a contributor you are allowed to clean up aswel. Keeping unused paths will only cause trouble in the long run

**Comment by tomkeuper** [comment]
Is it possible to remove the old paths so we can merge this?

**Comment by m7mqdev** [comment]
Alright I will remove them today or tomorrow. However, after thinking about it, the whole plugin needs a better design structure, so you guys should really consider doing a remake in my opinion.

**Comment by tomkeuper** [comment]
Easier said than done... if you want you can help :)

**Comment by tomkeuper** [comment]
bump

**Pull request closed without merging**
