### PR TITLE
fix invisibility potion compatibility with 1.8.8 and scoreboard improvements

### LINKED ISSUE #681: Player Health Under Name In Lobby
**Describe the bug**
When a player joins the server, I can see player health under their nametag in the lobby.

**To Reproduce**
1. Go to server
2. Come closer to NPCs
3. See player health under name in lobby

**Expected behavior**
I'm not sure if this is a feature or not, however, it would make more sense if we don't have that in the lobby.

**Screenshots**
image
image

**System (please complete the following information):**
 - OS: Windows
 - Server software: NachoSpigot
 - Server Version: 1.8.8
 - Plugin Version: v23.2

**Additional context**
If this is a feature in the lobby, please make a configuration option to disable this.

### LINKED ISSUE #688: Invisibile player nametag visible after drinking potion on 1.8
**Describe the bug**
When running a 1.8.8 server 1.8.x clients can see the nametag of an invisible player

**To Reproduce**
1. Drink an invisbility potion
2. look at invisible player from 1.8 client

**Expected behavior**
Nametag doenst show on all clients

**Screenshots**
https://prnt.sc/nEBt_FVR0wzG

**System (please complete the following information):**
 - OS: Linux
 - Server software Paperspigot
 - Server Version 1.8.8
 - Plugin Version 23.2.1-BETA2

### LINKED ISSUE #712: Tab prefix from game to lobby
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - Server software  Pufferfish version git-Pufferfish-60 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 52307ae on HEAD)
 - Server Version  1.19.3
 - Plugin Version  dev build

**Additional context**

### PR DESCRIPTION
**Pull request by andrei1058**
fix #688 
fix #712
fix #681

### CODE REVIEW

**Review by tomkeuper — APPROVED** [review]

**Comment by andrei1058** [comment]
I made some changes because the sidebar holder was getting header-footer strings in tab-subject's language. It was also triggering header-footer updade every single time a tab-subject was updated.

**Comment by tomkeuper** [comment]
Im quite sure that the only thing that still needs to happen is making he namtag visible again when the player gets out of invis.
as decribed here: https://discord.com/channels/201345265821679617/1074361958876315698/1083653985325551636

**Comment by andrei1058** [comment]
> Im quite sure that the only thing that still needs to happen is making he namtag visible again when the player gets out of invis. as decribed here: https://discord.com/channels/201345265821679617/1074361958876315698/1083653985325551636

Can't reproduce that

**Comment by tomkeuper** [comment]
Did you test on 1.8.8? That where the issue occurs

**Comment by tomkeuper** [comment]
How tf did I merge my branch into 668? ugh...

**Pull request merged**
