### PR TITLE
Added LuckyBlocks community addon to README.md

### PR DESCRIPTION
**Pull request by danirod12**
Last commit was canceled because i not a contributor. Now i am already a contributor.

Added LuckyBlocks NTD community addon

### CODE REVIEW

**Review by ProtoGhost — APPROVED** [review]

**Comment by SreyasIN** [comment]
Bruh no one buys that addon cuz it's not that useful.
Would've been better if free.
Also if you want your plugin to bol w up make it free.

**Comment by danirod12** [comment]
> Bruh no one buys that addon cuz it's not that useful.
> Would've been better if free.
> Also if you want your plugin to bol w up make it free.

Well, there is quite a lot of purchases. Try to visit the resource page. I’m not going to quarrel, but if something doesn’t suit you and you don’t have money, then you don’t need to express it. Nobody cares about it.

Buyers think the resource is great

**Review by MherZaqaryan — APPROVED** [review]

**Comment by ghost** [comment]
btw @danirod12 can you somehow add ice bridge to the plugin.
It wouldve been better if it was exactly like hypixel.
add a config called hypixel.yml for bedwars1058 with all the hypixel drops XD
btw i am a buyer.

**Comment by danirod12** [comment]
> btw @danirod12 can you somehow add ice bridge to the plugin. It wouldve been better if it was exactly like hypixel. add a config called hypixel.yml for bedwars1058 with all the hypixel drops XD btw i am a buyer.

This feature already requested and inside my todo-list

**Comment by ghost** [comment]
I think my trash cousin did ask for that XD

**Pull request merged**
