### PR TITLE
WIP: Fix bow boosting

### PR DESCRIPTION
**Pull request by ImYenil**
Fix bow boosting

What is bow boosting?
https://www.youtube.com/watch?v=R5t0pm8OarQ

### CODE REVIEW

**Comment by andrei1058** [comment]
We need to see if the damage is still given when the event is cancelled

**Comment by ImYenil** [comment]
> We need to see if the damage is still given when the event is cancelled

Have you checked?

**Comment by andrei1058** [comment]
Why did you close it

**Comment by ImYenil** [comment]
> Why did you close it

My PC was hacked so this repo was unusable and closed automatically. After you confirm it will be available in the next update

**Pull request closed without merging**
