### PR TITLE
Add vault rewards

### PR DESCRIPTION
**Pull request by josemarcellio**

### CODE REVIEW

**Comment by andrei1058** [comment]
At this point we should make it richer and add "per-kill-money" and so on. Where 0 money means disabled.

**Comment by Xxyuri2005xX** [comment]
I also suggest in the levels addong the player kill, final kill and bed destroyed give XP, same for economy

**Comment by josemarcellio** [comment]
alright

**Comment by andrei1058** [comment]
You could have kept the same pull request, lol

**Comment by josemarcellio** [comment]
ok sorry

**Pull request closed without merging**
