### PR TITLE
Update Spanish.java

### PR DESCRIPTION
**Pull request by Danidev819-TG**
Spanish was not well translated

### CODE REVIEW

**Comment by andrei1058** [comment]
We only need to test the yml syntax.

**Comment by Danidev819-TG** [comment]
image
image
image

**Review by Danidev819-TG — COMMENTED** [review]
;(

**Comment by andrei1058** [comment]
All good, we added some new paths in the mean time. Can you please translate the following as well?:
 yml.addDefault(Messages.MONEY_REWARD_PER_MINUTE, "{prefix}&6+{money} Coins (Play Time).");
        yml.addDefault(Messages.MONEY_REWARD_WIN, "{prefix}&6+{money} Coins (Game Win).");
        yml.addDefault(Messages.MONEY_REWARD_PER_TEAMMATE, "{prefix}&6+{money} Coins (Team Support).");
        yml.addDefault(Messages.MONEY_REWARD_BED_DESTROYED, "{prefix}&6+{money} Coins (Bed Destroyed).");
        yml.addDefault(Messages.MONEY_REWARD_FINAL_KILL, "{prefix}&6+{money} Coins (Final Kill).");
        yml.addDefault(Messages.MONEY_REWARD_REGULAR_KILL, "{prefix}&6+{money} Coins (Regular Kill).");

**Comment by Danidev819-TG** [comment]
Yup

**Review by Danidev819-TG — COMMENTED** [review]
I just added it :D

**Comment by andrei1058** [comment]
Good, but there are merge conflicts because you did not align to my master, I can't fix the conflict from my phone unfortunately

**Comment by Danidev819-TG** [comment]
> Good, but there are merge conflicts because you did not align to my master, I can't fix the conflict from my phone unfortunately

Solved

**Pull request merged**
