### PR TITLE
{Player} placeholder in messages

### LINKED ISSUE #258: Add `{playername}` placeholder in game death messages
**Is your feature request related to a problem? Please describe.**
In the death messages of the games the `{playername}` placeholder  does not work much less the placeholders of the PlaceholderAPI. Some people want to show the players name only, not the display name.

**Describe the solution you'd like**
Add `{playername}` placeholder in game death messages (`player-die-etc`)

**Describe alternatives you've considered**
Nothing

### PR DESCRIPTION
**Pull request by reussy**
Added {Player} placeholder for get the player name.

Closes #258

### CODE REVIEW

**Comment by andrei1058** [comment]
the way placeholders are starting to work in this plugin is really bad. people is coming with PR adding different-styled placeholders that in other cases act different or worse, they are not documented and no one knows about them nor how to use them. I'd like to accept this PR but we need to think about that and find a way to document them or making them global.

**Comment by reussy** [comment]
> the way placeholders are starting to work in this plugin is really bad. people is coming with PR adding different-styled placeholders that in other cases act different or worse, they are not documented and no one knows about them nor how to use them. I'd like to accept this PR but we need to thing about that and find a way to document them or making them global.

Yes, personally I see it as a total mess of placeholders, the best thing to do is to rework and make everything more homogeneous

**Comment by ajgeiss0702** [comment]
Yeah, I agree that the placeholders are all wonky. In some places {player} is the player name and in others it’s the display name. The issue is that if we change it, it could mess up some people’s configs. 

That might be a minor issue so maybe we should just bite the bullet and reformat all the placeholders to be more standard.

E.g. {displayname} for the players displayname, {playername} for the player name

**Comment by andrei1058** [comment]
I will close it for now. Let's plan a rework of placeholders!

**Pull request closed without merging**
