### PR TITLE
Hypixel Default

### PR DESCRIPTION
**Pull request by sreyas0001**
Hypixel Like Configs,Levels,Shop Cost,Fireball.Sounds Etc

### CODE REVIEW

**Comment by sreyas0001** [comment]
Would have been cool if there was a way to edit every single number from 1000-1099 etc in a single line

**Comment by Xxyuri2005xX** [comment]
why you made this dude? was enough for you doing it yourself in config files and just giving yml file or creating a resource on SpigotMC/MCMarket/Polymart

**Comment by sreyas0001** [comment]
> why you made this dude? was enough for you doing it yourself in config files and just giving yml file or creating a resource on SpigotMC/MCMarket/Polymart

Who would not like it being added by default
Prestiges is not complete as there is no shortcut for doing per-number editing in a range.
Like Maybe 1000-1099-name: &a[{number_1}&1{number_2}&b{number_3}&4{number_4}✪]

**Comment by Xxyuri2005xX** [comment]
Bedwars1058 is hypixel inspired, not a copy, amd this files you can just setup them in yml files and giving to community as resource on mcmarket, not everyone wants a bedwars plugin hypixel based, 1058 is known for customization

**Comment by sreyas0001** [comment]
> Bedwars1058 is hypixel inspired, not a copy, amd this files you can just setup them in yml files and giving to community as resource on mcmarket, not everyone wants a bedwars plugin hypixel based, 1058 is known for customization

It can still be customized though lol.... Its just for ease of use

**Comment by pukislukis** [comment]
> > Bedwars1058 is hypixel inspired, not a copy, amd this files you can just setup them in yml files and giving to community as resource on mcmarket, not everyone wants a bedwars plugin hypixel based, 1058 is known for customization
> 
> It can still be customized though lol.... Its just for ease of use

https://www.mc-market.org/resources/20750/
if you want prestige level config like hypixel

**Comment by Xxyuri2005xX** [comment]
> > > Bedwars1058 is hypixel inspired, not a copy, amd this files you can just setup them in yml files and giving to community as resource on mcmarket, not everyone wants a bedwars plugin hypixel based, 1058 is known for customization
> > 
> > 
> > It can still be customized though lol.... Its just for ease of use
> 
> https://www.mc-market.org/resources/20750/ if you want prestige level config like hypixel

idk why you gave me it, i already have it and i don't copy hypixel 😕

**Comment by Eradiator** [comment]
I guess this is useless but you can make pr for levels alone😄 for our easier use. And people can have better understanding of the levels customisation

**Comment by Eradiator** [comment]
Sounds.yml is also good.
But people may not want it.
But i need it default to the plugin😂

**Comment by Eradiator** [comment]
> Sounds.yml is also good. But people may not want it. But i need it default to the plugin😂

Because i dont know how different versions do with it.......
Version change=Ambient_thunder LOL

**Comment by Eradiator** [comment]
> Bedwars1058 is hypixel inspired, not a copy, amd this files you can just setup them in yml files and giving to community as resource on mcmarket, not everyone wants a bedwars plugin hypixel based, 1058 is known for customization

I think adding it default is not a bad idea.
Because in many minecraft servers using bw1058
Uses the default shop, level, etc which is boring tbh,, so if it gets changed then the server would look cooler.
I dont like the fact that kb sticks cost 10 instead of 5, egg 3 instead of 1

**Comment by dG9hc3Q** [comment]
this would be better if you edited the .ymls directly and put them into a zip on mcmarket or polymart

**Comment by NoJokeFNA** [comment]
Please squash your commits, this is a *commit-disaster*

**Comment by Eradiator** [comment]
> Please squash your commits, this is a _commit-disaster_

Ya, i guess it would be better if he squashes it...
but i guess i would like to see only the Sounds and Prestiges
oh the language is fix for a missing `:` lol

**Comment by Eradiator** [comment]
You Might Delete This PR IT SUCKS AF
otherthan than The Sounds LOL
The Sounds config is good it will wrk for 1.8+

**Pull request closed without merging**
